version: "3"
services:
  clickhouse:
    image: yandex/clickhouse-server
    ports:
    - "8123:8123"
    - "9000:9000"
    networks:
      simple_network:

  grafana:
    image: grafana/grafana
    depends_on:
      - web
    ports:
     - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,vertamedia-clickhouse-datasource"
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: "vertamedia-clickhouse-datasource"
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    networks:
      simple_network:

  web:
    build: web/
    user: root
    depends_on:
      - clickhouse
    command:
      ./init.sh
    ports:
      - "9980:80"
    networks:
      simple_network:
networks:
  simple_network:
    driver: bridge
